### ISSUE TITLE
사진 CRUD 기능

### ISSUE THREAD

**Issue by minjeong073** [donggukthonN/donggukthon_2023_7_B#7]
## 설명

업로드 된 사진을 저장하고, 조회, 수정 및 삭제하는 기능

### TODO

- [x] S3 연동
- [x] 업로드 사진 저장
- [ ] S3 bucket 에 임시 데이터 생성
- [x] 사진 리스트 조회
- [x] 사진 정렬
- [x] 사진 좋아요 기능
- [x] 사진 검색 기능
